name: Patch ZXing ESM

on:
  workflow_dispatch: {}

permissions:
  contents: write    # ← これが無いと push できない

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure .nojekyll
        run: |
          [ -f .nojekyll ] || touch .nojekyll

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Write patch script
        run: |
          mkdir -p tools
          cat > tools/fix-esm-imports.mjs << 'EOF'
          import { promises as fs } from 'fs';
          import path from 'path';
          const roots = [
            'vendor/zxing/browser/0.1.5/esm',
            'vendor/zxing/library/0.20.0/esm',
          ];
          function patchSpec(s) {
            if (!(s.startsWith('./') || s.startsWith('../'))) return s;
            if (s.endsWith('.js') || s.endsWith('.mjs')) return s;
            return s + '.js';
          }
          async function patchFile(fp) {
            let src = await fs.readFile(fp, 'utf8');
            const before = src;
            src = src.replace(/(from\s*['"])(\.\.?\/[^'"]+)(['"])/g,
              (_m, a, p, b) => a + patchSpec(p) + b);
            src = src.replace(/(import\s*\(\s*['"])(\.\.?\/[^'"]+)(['"]\s*\))/g,
              (_m, a, p, b) => a + patchSpec(p) + b);
            if (src !== before) await fs.writeFile(fp, src);
          }
          async function walk(dir) {
            const ents = await fs.readdir(dir, { withFileTypes: true });
            for (const e of ents) {
              const p = path.join(dir, e.name);
              if (e.isDirectory()) await walk(p);
              else if (e.isFile() && p.endsWith('.js')) await patchFile(p);
            }
          }
          for (const r of roots) { try { await walk(r); console.log('Patched:', r); } catch {} }
          console.log('Done.');
          EOF

      - name: Run patch
        run: node tools/fix-esm-imports.mjs

      - name: Commit & Push
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .nojekyll tools vendor/zxing/browser/0.1.5/esm vendor/zxing/library/0.20.0/esm
            git commit -m "chore(pages): patch ZXing ESM imports"
            git push
          else
            echo "No changes to commit."
          fi
